name: dbt CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-test:
    name: Run dbt Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core==1.7.0 dbt-snowflake==1.7.0

      - name: Remove repo profiles.yml
        run: rm -f ./market_pulse/profiles.yml

      - name: Create profiles.yml
        run: |
          mkdir -p /tmp/dbt_profiles
          cat > /tmp/dbt_profiles/profiles.yml << EOF
          market_pulse:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: EBSQBLV-NJ71987
                user: ALENJOSEPH7
                password: "${{ secrets.SNOWFLAKE_PASSWORD }}"
                role: TRANSFORMER
                database: STAGING
                warehouse: TRANSFORMER_WH
                schema: CORE
                threads: 4
          EOF

      - name: dbt debug
        working-directory: ./market_pulse
        run: dbt debug --profiles-dir /tmp/dbt_profiles

      - name: dbt run
        working-directory: ./market_pulse
        run: dbt run --profiles-dir /tmp/dbt_profiles --target prod

      - name: dbt test
        working-directory: ./market_pulse
        run: dbt test --profiles-dir /tmp/dbt_profiles --target prod